// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANsmOsJBT7NLpDcaj0_aBk15NfHUpm4uY',
    appId: '1:729663534271:web:ea50c93fec7db6eb00c20a',
    messagingSenderId: '729663534271',
    projectId: 'chat-app-81bd9',
    authDomain: 'chat-app-81bd9.firebaseapp.com',
    storageBucket: 'chat-app-81bd9.firebasestorage.app',
    measurementId: 'G-0EFFB0M102',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8hBojDKNpRWk9s2igrKh7HW7C8NcMkYI',
    appId: '1:729663534271:android:5373cd7dab54ec8f00c20a',
    messagingSenderId: '729663534271',
    projectId: 'chat-app-81bd9',
    storageBucket: 'chat-app-81bd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADJsokE7K2_P6x3zAYh2W-WCE8Brvx2wA',
    appId: '1:729663534271:ios:053ec88d7ee682bf00c20a',
    messagingSenderId: '729663534271',
    projectId: 'chat-app-81bd9',
    storageBucket: 'chat-app-81bd9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
